<?php

use Illuminate\Database\Seeder;
use Silber\Bouncer\Bouncer;
use App\Models\Store\Category;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // First, truncate categories table
        //Category::truncate();

        // Get default categories
        $defs = $this->getInitialCategories();

        // Create
        foreach( $defs as $cat )
        {
            echo $cat['name'] . PHP_EOL;

            $node = Category::create( $cat );
        }
    }

    /**
     * Returns the array with initial categories
     *
     * @return array
     */
    protected function getInitialCategories()
    {
        $categories = [
            [
                'name' => 'Lifestyle',
                'slug' => slug('Lifestyle'),
                'children' => [
                    [
                        'name' => 'Fitness & Saúde',
                        'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde'),
                        'children' => [
                            [ 'name' => 'Roupas',                      'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('Roupas') ],
                            [ 'name' => 'Acessórios',                  'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('Acessórios') ],
                            [ 'name' => 'Equipamentos',                'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('Equipamentos') ],
                            [ 'name' => 'Bolsa de primeiros socorros', 'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('Bolsa de primeiros socorros') ],
                            [ 'name' => 'Porta Remédio',               'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('Porta Remédio') ],
                            [ 'name' => 'OUTROS',                      'slug' => slug('Lifestyle') .'/'. slug('Fitness & Saúde') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Festa',
                        'slug' => slug('Lifestyle') .'/'. slug('Festa'),
                        'children' => [
                            [ 'name' => 'Convite',               'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Convite') ],
                            [ 'name' => 'Brinde',                'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Brinde') ],
                            [ 'name' => 'Decoração',             'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Decoração') ],
                            [ 'name' => 'Fantasia',              'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Fantasia') ],
                            [ 'name' => 'Embalagem de Presente', 'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Embalagem de presente') ],
                            [ 'name' => 'Cartão Comemorativo',   'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Cartão comemorativo') ],
                            [ 'name' => 'Casamento',             'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Casamento') ],
                            [ 'name' => 'Despedida de solteiro', 'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Despedida de solteiro') ],
                            [ 'name' => 'Chá revelação',         'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Chá revelação') ],
                            [ 'name' => 'Natal',                 'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Natal') ],
                            [ 'name' => 'Páscoa',                'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Páscoa') ],
                            [ 'name' => 'Festa Junina',          'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Festa junina') ],
                            [ 'name' => 'Ação de Graças',        'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Ação de graças') ],
                            [ 'name' => 'Halloween',             'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Halloween') ],
                            [ 'name' => 'Ano Novo',              'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Ano Novo') ],
                            [ 'name' => 'Carnaval',              'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('Carnaval') ],
                            [ 'name' => 'OUTROS',                'slug' => slug('Lifestyle') .'/'. slug('Festa') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Hobbies e Entretenimento',
                        'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento'),
                        'children' => [
                            [ 'name' => 'Música',           'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Música') ],
                            [ 'name' => 'Arte',             'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Arte') ],
                            [ 'name' => 'Maquiagem',        'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Maquiagem') ],
                            [ 'name' => 'Penteados',        'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Penteados') ],
                            [ 'name' => 'Fotografia',       'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Fotografia') ],
                            [ 'name' => 'RPG',              'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('RPG') ],
                            [ 'name' => 'Livro & Livreto',  'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Livro & Livreto') ],
                            [ 'name' => 'Livro de Colorir', 'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('Livro de Colorir') ],
                            [ 'name' => 'OUTROS',           'slug' => slug('Lifestyle') .'/'. slug('Hobbies e Entretenimento') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Fandom',
                        'slug' => slug('Lifestyle') .'/'. slug('Fandom'),
                        'children' => [
                            [ 'name' => 'Harry Potter',     'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Harry Potter') ],
                            [ 'name' => 'Game of Thrones',  'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Game of Thrones') ],
                            [ 'name' => 'Anime',            'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Anime') ],
                            [ 'name' => 'Senhor dos Anéis', 'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Senhor dos Anéis') ],
                            [ 'name' => 'Friends',          'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Friends') ],
                            [ 'name' => 'La Casa de Papel', 'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('La Casa de Papel') ],
                            [ 'name' => 'Beatles',          'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Beatles') ],
                            [ 'name' => 'Kardashians',      'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Kardashians') ],
                            [ 'name' => 'Gossip Girl',      'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Gossip Girl') ],
                            [ 'name' => 'Memes',            'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Memes') ],
                            [ 'name' => 'Star Wars',        'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Star Wars') ],
                            [ 'name' => 'Pokemon',          'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Pokemon') ],
                            [ 'name' => 'Marvel',           'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Marvel') ],
                            [ 'name' => 'DC',               'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('DC') ],
                            [ 'name' => 'Disney',           'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Disney') ],
                            [ 'name' => 'Cinema',           'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Cinema') ],
                            [ 'name' => 'Música',           'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('Música') ],
                            [ 'name' => 'OUTROS',           'slug' => slug('Lifestyle') .'/'. slug('Fandom') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Floricultura',
                        'slug' => slug('Lifestyle') .'/'. slug('Floricultura'),
                        'children' => [
                            [ 'name' => 'Buquê',               'slug' => slug('Lifestyle') .'/'. slug('Floricultura') .'/'. slug('Buquê'), ],
                            [ 'name' => 'Arranjo',             'slug' => slug('Lifestyle') .'/'. slug('Floricultura') .'/'. slug('Arranjo'), ],
                            [ 'name' => 'Datas comemorativas', 'slug' => slug('Lifestyle') .'/'. slug('Floricultura') .'/'. slug('Datas comemorativas'), ],
                            [ 'name' => 'OUTROS',              'slug' => slug('Lifestyle') .'/'. slug('Floricultura') .'/'. slug('OUTROS'), ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Lifestyle') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Kids',
                'slug' => slug('Kids'),
                'children' => [
                    [
                        'name' => 'Brinquedos e Jogos',
                        'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos'),
                        'children' => [
                            [ 'name' => 'Pelúcia',               'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Pelúcia') ],
                            [ 'name' => 'Educativo',             'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Educativo') ],
                            [ 'name' => 'Carro',                 'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Carro') ],
                            [ 'name' => 'Boneca',                'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Boneca') ],
                            [ 'name' => 'Tabuleiro',             'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Tabuleiro') ],
                            [ 'name' => 'Animais',               'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Animais') ],
                            [ 'name' => 'Bola',                  'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Bola') ],
                            [ 'name' => 'Bebê',                  'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Bebê') ],
                            [ 'name' => 'Brinquedos de Madeira', 'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Brinquedos de Madeira') ],
                            [ 'name' => 'Praia & Piscina',       'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Casa de Boneca',        'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('Casa de Boneca') ],
                            [ 'name' => 'OUTROS',                'slug' => slug('Kids') .'/'. slug('Brinquedos e Jogos') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Roupas',
                        'slug' => slug('Kids') .'/'. slug('Roupas'),
                        'children' => [
                            [ 'name' => 'Blusas',          'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Blusas') ],
                            [ 'name' => 'Calças',          'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Calças') ],
                            [ 'name' => 'Casacos',         'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Casacos') ],
                            [ 'name' => 'Macacão',         'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Macacão') ],
                            [ 'name' => 'Saias',           'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Saias') ],
                            [ 'name' => 'Short',           'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Short') ],
                            [ 'name' => 'Vestido',         'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Vestido') ],
                            [ 'name' => 'Festa',           'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Festa') ],
                            [ 'name' => 'Praia & Piscina', 'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Pijama',          'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Pijama') ],
                            [ 'name' => 'Roupa de baixo',  'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Roupa de baixo') ],
                            [ 'name' => 'Meia',            'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Meia') ],
                            [ 'name' => 'Fantasia',        'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Fantasia') ],
                            [ 'name' => 'Body',            'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Body') ],
                            [ 'name' => 'Inverno',         'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('Inverno') ],
                            [ 'name' => 'OUTROS',          'slug' => slug('Kids') .'/'. slug('Roupas') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Sapatos',
                        'slug' => slug('Kids') .'/'. slug('Sapatos'),
                        'children' => [
                            [ 'name' => 'Sandália',  'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Sandália') ],
                            [ 'name' => 'Tênis',     'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Tênis') ],
                            [ 'name' => 'Chinelo',   'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Chinelo') ],
                            [ 'name' => 'Bota',      'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Bota') ],
                            [ 'name' => 'Sapatilha', 'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Sapatilha') ],
                            [ 'name' => 'Mocassim',  'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Mocassim') ],
                            [ 'name' => 'Pantufa',   'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('Pantufa') ],
                            [ 'name' => 'OUTROS',    'slug' => slug('Kids') .'/'. slug('Sapatos') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Acessórios',
                        'slug' => slug('Kids') .'/'. slug('Acessórios'),
                        'children' => [
                            [ 'name' => 'Bolsa',                'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Bolsa'), ],
                            [ 'name' => 'Mochila',              'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Mochila') ],
                            [ 'name' => 'Relógio',              'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Relógio') ],
                            [ 'name' => 'Bijoux',               'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Bijoux') ],
                            [ 'name' => 'Semi-Joia',            'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Semi-Joia') ],
                            [ 'name' => 'Joia',                 'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Joia') ],
                            [ 'name' => 'Cinto',                'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Cinto') ],
                            [ 'name' => 'Carteira',             'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Carteira') ],
                            [ 'name' => 'Lenço',                'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Lenço') ],
                            [ 'name' => 'Acessórios de cabeça', 'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Acessórios de cabeça') ],
                            [ 'name' => 'Inverno',              'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Inverno') ],
                            [ 'name' => 'Praia & Piscina',      'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Prendedor de chupeta', 'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('Prendedor de chupeta') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Kids') .'/'. slug('Acessórios') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Móveis e Decoração',
                        'slug' => slug('Kids') .'/'. slug('Móveis e Decoração'),
                        'children' => [
                            [ 'name' => 'Berço',                'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Berço'), ],
                            [ 'name' => 'Trocador',             'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Trocador') ],
                            [ 'name' => 'Chiqueirinho',         'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Chiqueirinho') ],
                            [ 'name' => 'Cadeira',              'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Cadeira') ],
                            [ 'name' => 'Mesinha',              'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Mesinha') ],
                            [ 'name' => 'Mini cama',            'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Mini cama') ],
                            [ 'name' => 'Baú de Brinquedos',    'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Baú de Brinquedos') ],
                            [ 'name' => 'Poltrona',             'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Poltrona') ],
                            [ 'name' => 'Enfeites de parede',   'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Enfeites de parede') ],
                            [ 'name' => 'Enfeites de Porta',    'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Enfeites de Porta') ],
                            [ 'name' => 'Nichos & Prateleiras', 'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Nichos & Prateleiras') ],
                            [ 'name' => 'Mobile',               'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Mobile') ],
                            [ 'name' => 'Luz noturna',          'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('Luz noturna') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Kids') .'/'. slug('Móveis e Decoração') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Passeio',
                        'slug' => slug('Kids') .'/'. slug('Passeio'),
                        'children' => [
                            [ 'name' => 'Carrinho',                 'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Carrinho') ],
                            [ 'name' => 'Bolsa De Bebê',            'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Bolsa De Bebê') ],
                            [ 'name' => 'Canguru',                  'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Canguru') ],
                            [ 'name' => 'Porta Papinha',            'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Porta Papinha') ],
                            [ 'name' => 'Mochila Guia',             'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Mochila Guia') ],
                            [ 'name' => 'Kit Higiene',              'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Kit Higiene') ],
                            [ 'name' => 'Bolsa térmica',            'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Bolsa térmica') ],
                            [ 'name' => 'Acessórios para Carrinho', 'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('Acessórios para Carrinho') ],
                            [ 'name' => 'OUTROS',                   'slug' => slug('Kids') .'/'. slug('Passeio') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Organização',
                        'slug' => slug('Kids') .'/'. slug('Organização'),
                        'children' => [
                            [ 'name' => 'Porta Fralda Suja', 'slug' => slug('Kids') .'/'. slug('Organização') .'/'. slug('Porta Fralda Suja') ],
                            [ 'name' => 'Porta Trecos',      'slug' => slug('Kids') .'/'. slug('Organização') .'/'. slug('Porta Trecos') ],
                            [ 'name' => 'Recipientes',       'slug' => slug('Kids') .'/'. slug('Organização') .'/'. slug('Recipientes') ],
                            [ 'name' => 'Cestas',            'slug' => slug('Kids') .'/'. slug('Organização') .'/'. slug('Cestas') ],
                            [ 'name' => 'OUTROS',            'slug' => slug('Kids') .'/'. slug('Organização') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Mini Me',
                        'slug' => slug('Kids') .'/'. slug('Mini Me'),
                        'children' => [
                            [ 'name' => 'Blusa',            'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Blusa') ],
                            [ 'name' => 'Calça',            'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Calça') ],
                            [ 'name' => 'Casaco',           'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Casaco') ],
                            [ 'name' => 'Fitness',          'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Fitness') ],
                            [ 'name' => 'Macacão',          'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Macacão') ],
                            [ 'name' => 'Saia',             'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Saia') ],
                            [ 'name' => 'Short',            'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Short') ],
                            [ 'name' => 'Vestido',          'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Vestido') ],
                            [ 'name' => 'Festa',            'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Festa') ],
                            [ 'name' => 'Praia & Piscina ', 'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Roupa de Baixo',   'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Roupa de Baixo') ],
                            [ 'name' => 'Pijama',           'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Pijama') ],
                            [ 'name' => 'Meia',             'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Meia') ],
                            [ 'name' => 'Fantasia',         'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('Fantasia') ],
                            [ 'name' => 'OUTROS',           'slug' => slug('Kids') .'/'. slug('Mini Me') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Enxoval',
                        'slug' => slug('Kids') .'/'. slug('Enxoval'),
                        'children' => [
                            [ 'name' => 'Manta',                'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Manta') ],
                            [ 'name' => 'Travesseiro',          'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Travesseiro') ],
                            [ 'name' => 'Kit Montessoriano',    'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Kit Montessoriano') ],
                            [ 'name' => 'Protetor de Berço',    'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Protetor de Berço') ],
                            [ 'name' => 'Cortina',              'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Cortina') ],
                            [ 'name' => 'Babador',              'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Babador') ],
                            [ 'name' => 'Toalha de Boca',       'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Toalha de Boca') ],
                            [ 'name' => 'Naninha',              'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Naninha') ],
                            [ 'name' => 'Mosquiteiro',          'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Mosquiteiro') ],
                            [ 'name' => 'Enxoval',              'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Enxoval') ],
                            [ 'name' => 'Bolsa de Maternidade', 'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Bolsa de Maternidade') ],
                            [ 'name' => 'Toalha de Banho',      'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Toalha de Banho') ],
                            [ 'name' => 'Roupão',               'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Roupão') ],
                            [ 'name' => 'Almofada',             'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('Almofada') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Kids') .'/'. slug('Enxoval') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Kids') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Casa',
                'slug' => slug('Casa'),
                'children' => [
                    [
                        'name' => 'Móveis',
                        'slug' => slug('Casa') .'/'. slug('Móveis'),
                        'children' => [
                            [ 'name' => 'Cadeira',           'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Cadeira') ],
                            [ 'name' => 'Mesa',              'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Mesa') ],
                            [ 'name' => 'Poltrona',          'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Poltrona') ],
                            [ 'name' => 'Sofá',              'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Sofá') ],
                            [ 'name' => 'Pufe',              'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Pufe') ],
                            [ 'name' => 'Baú',               'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Baú') ],
                            [ 'name' => 'Banco',             'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Banco') ],
                            [ 'name' => 'Recamier',          'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Recamier') ],
                            [ 'name' => 'Mesa de Centro',    'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Mesa de Centro') ],
                            [ 'name' => 'Mesa de Cabeceira', 'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Mesa de Cabeceira') ],
                            [ 'name' => 'Mesa Lateral',      'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Mesa Lateral') ],
                            [ 'name' => 'Criado Mudo',       'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Criado Mudo') ],
                            [ 'name' => 'Penteadeira',       'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Penteadeira') ],
                            [ 'name' => 'Bar',               'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('Bar') ],
                            [ 'name' => 'OUTROS',            'slug' => slug('Casa') .'/'. slug('Móveis') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Decoração',
                        'slug' => slug('Casa') .'/'. slug('Decoração'),
                        'children' => [
                            [ 'name' => 'Tapete',             'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Tapete') ],
                            [ 'name' => 'Arte/Quadro/Tela',   'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Arte_Quadro_Tela') ],
                            [ 'name' => 'Ilustração',         'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Ilustração') ],
                            [ 'name' => 'Moldura',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Moldura') ],
                            [ 'name' => 'Porta Retrato',      'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Porta Retrato') ],
                            [ 'name' => 'Vaso',               'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Vaso') ],
                            [ 'name' => 'Manta',              'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Manta') ],
                            [ 'name' => 'Almofada',           'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Almofada') ],
                            [ 'name' => 'Cesta',              'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Cesta') ],
                            [ 'name' => 'Cortina',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Cortina') ],
                            [ 'name' => 'Espelho',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Espelho') ],
                            [ 'name' => 'Abajour',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Abajour') ],
                            [ 'name' => 'Luminária',          'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Luminária') ],
                            [ 'name' => 'Capacho',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Capacho') ],
                            [ 'name' => 'Cachepot',           'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Cachepot') ],
                            [ 'name' => 'Lareira',            'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Lareira') ],
                            [ 'name' => 'Luminosos',          'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Luminosos') ],
                            [ 'name' => 'Vela',               'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Vela') ],
                            [ 'name' => 'Cristais',           'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Cristais') ],
                            [ 'name' => 'Escultura',          'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Escultura') ],
                            [ 'name' => 'Artigos Religiosos', 'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Artigos Religiosos') ],
                            [ 'name' => 'Papel de Parede',    'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Papel de Parede') ],
                            [ 'name' => 'Adesivo de Parede',  'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Adesivo de Parede') ],
                            [ 'name' => 'Miniaturas',         'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Miniaturas') ],
                            [ 'name' => 'Arte em Vidro',      'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Arte em Vidro') ],
                            [ 'name' => 'Arte em Fibra',      'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Arte em Fibra') ],
                            [ 'name' => 'Ímã',                'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('Ímã') ],
                            [ 'name' => 'OUTROS',             'slug' => slug('Casa') .'/'. slug('Decoração') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Utilidades',
                        'slug' => slug('Casa') .'/'. slug('Utilidades'),
                        'children' => [
                            [ 'name' => 'Organizador de Maquiagem', 'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Organizador de Maquiagem') ],
                            [ 'name' => 'Porta Joia',               'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Porta Joia') ],
                            [ 'name' => 'Descanso de Jóia',         'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Descanso de Jóia') ],
                            [ 'name' => 'Cesto Organizador',        'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Cesto Organizador') ],
                            [ 'name' => 'Revisteiro',               'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Revisteiro') ],
                            [ 'name' => 'Porta Guarda-chuva',       'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Porta Guarda-chuva') ],
                            [ 'name' => 'Porta Chapéu',             'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Porta Chapéu') ],
                            [ 'name' => 'Porta Chave',              'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Porta Chave') ],
                            [ 'name' => 'Prateleira',               'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Prateleira') ],
                            [ 'name' => 'Nicho',                    'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Nicho') ],
                            [ 'name' => 'Carrinho Multiuso',        'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Carrinho Multiuso') ],
                            [ 'name' => 'Aromatizador',             'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Aromatizador') ],
                            [ 'name' => 'Aromas',                   'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Aromas') ],
                            [ 'name' => 'Cesto de Roupa Suja',      'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Cesto de Roupa Suja') ],
                            [ 'name' => 'Kit Lavabo',               'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('Kit Lavabo') ],
                            [ 'name' => 'OUTROS',                   'slug' => slug('Casa') .'/'. slug('Utilidades') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Bar & Cozinha',
                        'slug' => slug('Casa') .'/'. slug('Bar & Cozinha'),
                        'children' => [
                            [ 'name' => 'Anel Guardanapo',     'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Anel Guardanapo') ],
                            [ 'name' => 'Porta Utensilios',    'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Porta Utensilios') ],
                            [ 'name' => 'Pratos',              'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Pratos') ],
                            [ 'name' => 'Talheres',            'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Talheres') ],
                            [ 'name' => 'Xicaras',             'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Xicaras') ],
                            [ 'name' => 'Canecas',             'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Canecas') ],
                            [ 'name' => 'Guardanapo',          'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Guardanapo') ],
                            [ 'name' => 'Bowl',                'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Bowl') ],
                            [ 'name' => 'Suplat',              'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Suplat') ],
                            [ 'name' => 'Decoração de Mesa',   'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Decoração de Mesa') ],
                            [ 'name' => 'Porta Copos',         'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Porta Copos') ],
                            [ 'name' => 'Garrafas',            'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Garrafas') ],
                            [ 'name' => 'Petisqueira',         'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Petisqueira') ],
                            [ 'name' => 'Marcador de Taça',    'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Marcador de Taça') ],
                            [ 'name' => 'Misturador de Drink', 'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Misturador de Drink') ],
                            [ 'name' => 'Coqueteleira',        'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Coqueteleira') ],
                            [ 'name' => 'Balde de Gelo',       'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Balde de Gelo') ],
                            [ 'name' => 'Espeto para Petisco', 'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('Espeto para Petisco') ],
                            [ 'name' => 'OUTROS',              'slug' => slug('Casa') .'/'. slug('Bar & Cozinha') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Cama, Mesa e Banho',
                        'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho'),
                        'children' => [
                            [ 'name' => 'Lençol',                 'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Lençol') ],
                            [ 'name' => 'Cortina',                'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Cortina') ],
                            [ 'name' => 'Capa de Travesseiro',    'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Capa de Travesseiro') ],
                            [ 'name' => 'Edredon',                'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Edredon') ],
                            [ 'name' => 'Manta',                  'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Manta') ],
                            [ 'name' => 'Colcha',                 'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Colcha') ],
                            [ 'name' => 'Almofada',               'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Almofada') ],
                            [ 'name' => 'Organizador de Sapatos', 'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Organizador de Sapatos') ],
                            [ 'name' => 'Cabideiro',              'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Cabideiro') ],
                            [ 'name' => 'Capa de Colchão',        'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Capa de Colchão') ],
                            [ 'name' => 'Tapete de Banheiro',     'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Tapete de Banheiro') ],
                            [ 'name' => 'Toalha de Banho',        'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Toalha de Banho') ],
                            [ 'name' => 'Toalha de Rosto',        'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Toalha de Rosto') ],
                            [ 'name' => 'Toalha de Mão',          'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Toalha de Mão') ],
                            [ 'name' => 'Toalha de Cabelo',       'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Toalha de Cabelo') ],
                            [ 'name' => 'Jogo Americano',         'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Jogo Americano') ],
                            [ 'name' => 'Toalha de Mesa',         'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Toalha de Mesa') ],
                            [ 'name' => 'Guardanapo de Tecido',   'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('Guardanapo de Tecido') ],
                            [ 'name' => 'OUTROS',                 'slug' => slug('Casa') .'/'. slug('Cama, Mesa e Banho') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outdoors',
                        'slug' => slug('Casa') .'/'. slug('Outdoors'),
                        'children' => [
                            [ 'name' => 'Toalha de Piscina',      'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Toalha de Piscina') ],
                            [ 'name' => 'Boia',                   'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Boia') ],
                            [ 'name' => 'Decoração Jardim',       'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Decoração Jardim') ],
                            [ 'name' => 'Vaso',                   'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Vaso') ],
                            [ 'name' => 'Picnic',                 'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Picnic') ],
                            [ 'name' => 'Moveis Externos',        'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Moveis Externos') ],
                            [ 'name' => 'Estofados Impermeáveis', 'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Estofados Impermeáveis') ],
                            [ 'name' => 'Iluminação',             'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Iluminação') ],
                            [ 'name' => 'Som Ambiente',           'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('Som Ambiente') ],
                            [ 'name' => 'OUTROS',                 'slug' => slug('Casa') .'/'. slug('Outdoors') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Casa') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Pets',
                'slug' => slug('Pets'),
                'children' => [
                    [
                        'name' => 'Cachorros',
                        'slug' => slug('Pets') .'/'. slug('Cachorros'),
                        'children' => [
                            [ 'name' => 'Brinquedo',   'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Brinquedo') ],
                            [ 'name' => 'Roupa',       'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Roupa') ],
                            [ 'name' => 'Acessório',   'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Acessório') ],
                            [ 'name' => 'Passeio',     'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Passeio') ],
                            [ 'name' => 'Transporte',  'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Transporte') ],
                            [ 'name' => 'Alimentação', 'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Alimentação') ],
                            [ 'name' => 'Organização', 'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Organização') ],
                            [ 'name' => 'Cama',        'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('Cama') ],
                            [ 'name' => 'OUTROS',      'slug' => slug('Pets') .'/'. slug('Cachorros') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Gatos',
                        'slug' => slug('Pets') .'/'. slug('Gatos'),
                        'children' => [
                            [ 'name' => 'Brinquedo',   'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Brinquedo') ],
                            [ 'name' => 'Roupa',       'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Roupa') ],
                            [ 'name' => 'Acessório',   'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Acessório') ],
                            [ 'name' => 'Passeio',     'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Passeio') ],
                            [ 'name' => 'Transporte',  'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Transporte') ],
                            [ 'name' => 'Alimentação', 'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Alimentação') ],
                            [ 'name' => 'Organização', 'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Organização') ],
                            [ 'name' => 'Cama',        'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Cama') ],
                            [ 'name' => 'Torre',       'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('Torre') ],
                            [ 'name' => 'OUTROS',      'slug' => slug('Pets') .'/'. slug('Gatos') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Pássaros',
                        'slug' => slug('Pets') .'/'. slug('Pássaros'),
                        'children' => [
                            [ 'name' => 'Brinquedo',   'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Brinquedo') ],
                            [ 'name' => 'Acessório',   'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Acessório') ],
                            [ 'name' => 'Transporte',  'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Transporte') ],
                            [ 'name' => 'Alimentação', 'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Alimentação') ],
                            [ 'name' => 'Organização', 'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Organização') ],
                            [ 'name' => 'Gaiolas',     'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('Gaiolas') ],
                            [ 'name' => 'OUTROS',      'slug' => slug('Pets') .'/'. slug('Pássaros') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Roedores',
                        'slug' => slug('Pets') .'/'. slug('Roedores'),
                        'children' => [
                            [ 'name' => 'Brinquedo',   'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Brinquedo') ],
                            [ 'name' => 'Roupa',       'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Roupa') ],
                            [ 'name' => 'Acessório',   'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Acessório') ],
                            [ 'name' => 'Passeio',     'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Passeio') ],
                            [ 'name' => 'Alimentação', 'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Alimentação') ],
                            [ 'name' => 'Transporte',  'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Transporte') ],
                            [ 'name' => 'Organização', 'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Organização') ],
                            [ 'name' => 'Cama',        'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Cama') ],
                            [ 'name' => 'Gaiolas',     'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('Gaiolas') ],
                            [ 'name' => 'OUTROS',      'slug' => slug('Pets') .'/'. slug('Roedores') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Aquáticos',
                        'slug' => slug('Pets') .'/'. slug('Aquáticos'),
                        'children' => [
                            [ 'name' => 'Aquários',                   'slug' => slug('Pets') .'/'. slug('Aquáticos') .'/'. slug('Aquários') ],
                            [ 'name' => 'Acessórios de Aquário/Lago', 'slug' => slug('Pets') .'/'. slug('Aquáticos') .'/'. slug('Acessórios de Aquário-Lago') ],
                            [ 'name' => 'OUTROS',                     'slug' => slug('Pets') .'/'. slug('Aquáticos') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros Pets',
                        'slug' => slug('Pets') .'/'. slug('Outros Pets'),
                        'children' => [
                            [ 'name' => 'Tartarugas', 'slug' => slug('Pets') .'/'. slug('Outros Pets') .'/'. slug('Tartarugas') ],
                            [ 'name' => 'Lagartos',   'slug' => slug('Pets') .'/'. slug('Outros Pets') .'/'. slug('Lagartos') ],
                            [ 'name' => 'Cavalos',    'slug' => slug('Pets') .'/'. slug('Outros Pets') .'/'. slug('Cavalos') ],
                            [ 'name' => 'OUTROS',     'slug' => slug('Pets') .'/'. slug('Outros Pets') .'/'. slug('OUTROS') ],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Homens',
                'slug' => slug('Homens'),
                'children' => [
                    [
                        'name' => 'Acessórios',
                        'slug' => slug('Homens') .'/'. slug('Acessórios'),
                        'children' => [
                            [ 'name' => 'Bolsa',                'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Bolsa') ],
                            [ 'name' => 'Pochete',              'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Pochete') ],
                            [ 'name' => 'Relógio',              'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Relógio') ],
                            [ 'name' => 'Bijoux',               'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Bijoux') ],
                            [ 'name' => 'Semi-Joia',            'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Semi-Joia') ],
                            [ 'name' => 'Joia',                 'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Joia') ],
                            [ 'name' => 'Cinto',                'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Cinto') ],
                            [ 'name' => 'Carteira',             'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Carteira') ],
                            [ 'name' => 'Lenço',                'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Lenço') ],
                            [ 'name' => 'Acessórios de Cabeça', 'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Acessórios de Cabeça') ],
                            [ 'name' => 'Inverno',              'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Inverno') ],
                            [ 'name' => 'Praia & Piscina',      'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Homens') .'/'. slug('Acessórios') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Roupas',
                        'slug' => slug('Homens') .'/'. slug('Roupas'),
                        'children' => [
                            [ 'name' => 'Blusa',           'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Blusa') ],
                            [ 'name' => 'Colete',          'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Colete') ],
                            [ 'name' => 'Calça',           'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Calça') ],
                            [ 'name' => 'Camisa',          'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Camisa') ],
                            [ 'name' => 'Camiseta',        'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Camiseta') ],
                            [ 'name' => 'Casaco',          'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Casaco') ],
                            [ 'name' => 'Macacão',         'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Macacão') ],
                            [ 'name' => 'Short',           'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Short') ],
                            [ 'name' => 'Terno',           'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Terno') ],
                            [ 'name' => 'Festa',           'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Festa') ],
                            [ 'name' => 'Fitness',         'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Fitness') ],
                            [ 'name' => 'Praia & Piscina', 'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Roupa Íntima',    'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Roupa Íntima') ],
                            [ 'name' => 'Pijama',          'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Pijama') ],
                            [ 'name' => 'Work',            'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('Work') ],
                            [ 'name' => 'OUTROS',          'slug' => slug('Homens') .'/'. slug('Roupas') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Calçados',
                        'slug' => slug('Homens') .'/'. slug('Calçados'),
                        'children' => [
                            [ 'name' => 'Botas',     'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('Botas') ],
                            [ 'name' => 'Sandálias', 'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('Sandálias') ],
                            [ 'name' => 'Sapato',    'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('Sapato') ],
                            [ 'name' => 'Tenis',     'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('Tenis') ],
                            [ 'name' => 'Chinelo',   'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('Chinelo') ],
                            [ 'name' => 'OUTROS',    'slug' => slug('Homens') .'/'. slug('Calçados') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Homens') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Mulheres',
                'slug' => slug('Mulheres'),
                'children' => [
                    [
                        'name' => 'Acessórios',
                        'slug' => slug('Mulheres') .'/'. slug('Acessórios'),
                        'children' => [
                            [ 'name' => 'Bolsa',                'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Bolsa') ],
                            [ 'name' => 'Pochete',              'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Pochete') ],
                            [ 'name' => 'Relógio',              'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Relógio') ],
                            [ 'name' => 'Bijoux',               'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Bijoux') ],
                            [ 'name' => 'Semi-Joia',            'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Semi-Joia') ],
                            [ 'name' => 'Joia',                 'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Joia') ],
                            [ 'name' => 'Cinto',                'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Cinto') ],
                            [ 'name' => 'Carteira',             'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Carteira') ],
                            [ 'name' => 'Lenço',                'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Lenço') ],
                            [ 'name' => 'Acessórios de Cabeça', 'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Acessórios de Cabeça') ],
                            [ 'name' => 'Inverno',              'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Inverno') ],
                            [ 'name' => 'Praia & Piscina',      'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Mulheres') .'/'. slug('Acessórios') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Roupas',
                        'slug' => slug('Mulheres') .'/'. slug('Roupas'),
                        'children' => [
                            [ 'name' => 'Blusa',           'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Blusa') ],
                            [ 'name' => 'Colete',          'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Colete') ],
                            [ 'name' => 'Calça',           'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Calça') ],
                            [ 'name' => 'Camisa',          'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Camisa') ],
                            [ 'name' => 'Camiseta',        'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Camiseta') ],
                            [ 'name' => 'Casaco',          'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Casaco') ],
                            [ 'name' => 'Macacão',         'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Macacão') ],
                            [ 'name' => 'Saia',            'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Saia'), ],
                            [ 'name' => 'Short',           'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Short') ],
                            [ 'name' => 'Terno',           'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Terno') ],
                            [ 'name' => 'Vestido',         'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Vestido'), ],
                            [ 'name' => 'Festa',           'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Festa') ],
                            [ 'name' => 'Fitness',         'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Fitness') ],
                            [ 'name' => 'Praia & Piscina', 'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Roupa Íntima',    'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Roupa Íntima') ],
                            [ 'name' => 'Pijama',          'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Pijama') ],
                            [ 'name' => 'Work',            'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('Work') ],
                            [ 'name' => 'OUTROS',          'slug' => slug('Mulheres') .'/'. slug('Roupas') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Calçados',
                        'slug' => slug('Mulheres') .'/'. slug('Calçados'),
                        'children' => [
                            [ 'name' => 'Botas',        'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Botas') ],
                            [ 'name' => 'Sandálias',    'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Sandálias') ],
                            [ 'name' => 'Salto',        'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Salto'), ],
                            [ 'name' => 'Rasteirinhas', 'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Rasteirinhas'), ],
                            [ 'name' => 'Sapatilha',    'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Sapatilha'), ],
                            [ 'name' => 'Sapato',       'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Sapato') ],
                            [ 'name' => 'Tenis',        'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Tenis') ],
                            [ 'name' => 'Chinelo',      'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('Chinelo') ],
                            [ 'name' => 'OUTROS',       'slug' => slug('Mulheres') .'/'. slug('Calçados') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Mulheres') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Genderless',
                'slug' => slug('Genderless'),
                'children' => [
                    [
                        'name' => 'Acessórios',
                        'slug' => slug('Genderless') .'/'. slug('Acessórios'),
                        'children' => [
                            [ 'name' => 'Bolsa',                'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Bolsa') ],
                            [ 'name' => 'Pochete',              'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Pochete') ],
                            [ 'name' => 'Relógio',              'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Relógio') ],
                            [ 'name' => 'Bijoux',               'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Bijoux') ],
                            [ 'name' => 'Semi-Joia',            'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Semi-Joia') ],
                            [ 'name' => 'Joia',                 'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Joia') ],
                            [ 'name' => 'Cinto',                'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Cinto') ],
                            [ 'name' => 'Carteira',             'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Carteira') ],
                            [ 'name' => 'Lenço',                'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Lenço') ],
                            [ 'name' => 'Acessórios de Cabeça', 'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Acessórios de Cabeça') ],
                            [ 'name' => 'Inverno',              'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Inverno') ],
                            [ 'name' => 'Praia & Piscina',      'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'OUTROS',               'slug' => slug('Genderless') .'/'. slug('Acessórios') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Roupas',
                        'slug' => slug('Genderless') .'/'. slug('Roupas'),
                        'children' => [
                            [ 'name' => 'Blusa',           'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Blusa') ],
                            [ 'name' => 'Colete',          'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Colete') ],
                            [ 'name' => 'Calça',           'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Calça') ],
                            [ 'name' => 'Camisa',          'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Camisa') ],
                            [ 'name' => 'Camiseta',        'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Camiseta') ],
                            [ 'name' => 'Casaco',          'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Casaco') ],
                            [ 'name' => 'Macacão',         'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Macacão') ],
                            [ 'name' => 'Saia',            'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Saia'), ],
                            [ 'name' => 'Short',           'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Short') ],
                            [ 'name' => 'Terno',           'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Terno') ],
                            [ 'name' => 'Vestido',         'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Vestido'), ],
                            [ 'name' => 'Festa',           'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Festa') ],
                            [ 'name' => 'Fitness',         'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Fitness') ],
                            [ 'name' => 'Praia & Piscina', 'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Praia & Piscina') ],
                            [ 'name' => 'Roupa Íntima',    'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Roupa Íntima') ],
                            [ 'name' => 'Pijama',          'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Pijama') ],
                            [ 'name' => 'Work',            'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('Work') ],
                            [ 'name' => 'OUTROS',          'slug' => slug('Genderless') .'/'. slug('Roupas') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Calçados',
                        'slug' => slug('Genderless') .'/'. slug('Calçados'),
                        'children' => [
                            [ 'name' => 'Botas',        'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('Botas') ],
                            [ 'name' => 'Sandálias',    'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('Sandálias') ],
                            [ 'name' => 'Sapato',       'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('Sapato') ],
                            [ 'name' => 'Tenis',        'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('Tenis') ],
                            [ 'name' => 'Chinelo',      'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('Chinelo') ],
                            [ 'name' => 'OUTROS',       'slug' => slug('Genderless') .'/'. slug('Calçados') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Genderless') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'On the go',
                'slug' => slug('On the go'),
                'children' => [
                    [
                        'name' => 'Transporte',
                        'slug' => slug('On the go') .'/'. slug('Transporte'),
                        'children' => [
                            [ 'name' => 'Academia',            'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Academia') ],
                            [ 'name' => 'Weekend Getaway',     'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Weekend Getaway') ],
                            [ 'name' => 'Mala de Bordo',       'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Mala de Bordo') ],
                            [ 'name' => 'Mala para Despache',  'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Mala para Despache') ],
                            [ 'name' => 'Mala Under the Seat', 'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Mala Under the Seat') ],
                            [ 'name' => 'Bolsa Térmica',       'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Bolsa Térmica') ],
                            [ 'name' => 'Bolsa para Notebook', 'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Bolsa para Notebook') ],
                            [ 'name' => 'Pasta Executiva',     'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Pasta Executiva') ],
                            [ 'name' => 'Pasta Portfólio',     'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Pasta Portfólio') ],
                            [ 'name' => 'Transporte de Pets',  'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Transporte de Pets') ],
                            [ 'name' => 'Bolsa Escolar',       'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Bolsa Escolar') ],
                            [ 'name' => 'Pochete',             'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('Pochete') ],
                            [ 'name' => 'OUTROS',              'slug' => slug('On the go') .'/'. slug('Transporte') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Acessórios',
                        'slug' => slug('On the go') .'/'. slug('Acessórios'),
                        'children' => [
                            [ 'name' => 'Chaveiro',              'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Chaveiro') ],
                            [ 'name' => 'Garrafa Térmica',       'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Garrafa Térmica') ],
                            [ 'name' => 'Capa Passaporte',       'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Capa Passaporte') ],
                            [ 'name' => 'Tag Mala',              'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Tag Mala') ],
                            [ 'name' => 'Faixa de Mala',         'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Faixa de Mala') ],
                            [ 'name' => 'Máscara de Dormir',     'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Máscara de Dormir') ],
                            [ 'name' => 'Manta de Viagem',       'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Manta de Viagem') ],
                            [ 'name' => 'Travesseiro de Viagem', 'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Travesseiro de Viagem') ],
                            [ 'name' => 'Almofada de Pescoço',   'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Almofada de Pescoço') ],
                            [ 'name' => 'Adesivo para Mala',     'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Adesivo para Mala') ],
                            [ 'name' => 'Cadeado',               'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Cadeado') ],
                            [ 'name' => 'Lixo para Carro',       'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Lixo para Carro') ],
                            [ 'name' => 'Kit para Viagem',       'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('Kit para Viagem') ],
                            [ 'name' => 'OUTROS',                'slug' => slug('On the go') .'/'. slug('Acessórios') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Organização',
                        'slug' => slug('On the go') .'/'. slug('Organização'),
                        'children' => [
                            [ 'name' => 'Bolsa para Roupa Suja',              'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Bolsa para Roupa Suja') ],
                            [ 'name' => 'Bolsa para Lingerie',                'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Bolsa para Lingerie') ],
                            [ 'name' => 'Saco Organizador',                   'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Saco Organizador') ],
                            [ 'name' => 'Porta Joias para Viagem',            'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Porta Joias para Viagem') ],
                            [ 'name' => 'Necessaire',                         'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Necessaire') ],
                            [ 'name' => 'Porta Documentos',                   'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Porta Documentos') ],
                            [ 'name' => 'Carteira de Viagem',                 'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Carteira de Viagem') ],
                            [ 'name' => 'Bolsa de Cométicos',                 'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Bolsa de Cométicos') ],
                            [ 'name' => 'Organizador para Costas de Assento', 'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Organizador para Costas de Assento') ],
                            [ 'name' => 'Organizador para Carro',             'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Organizador para Carro') ],
                            [ 'name' => 'Bolsa para Remédios',                'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Bolsa para Remédios') ],
                            [ 'name' => 'Bolsa Interna',                      'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('Bolsa Interna') ],
                            [ 'name' => 'OUTROS',                             'slug' => slug('On the go') .'/'. slug('Organização') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('On the go') .'/'. slug('Outros'),
                    ],
                ],
            ],
            [
                'name' => 'Office',
                'slug' => slug('Office'),
                'children' => [
                    [
                        'name' => 'Papelaria',
                        'slug' => slug('Office') .'/'. slug('Papelaria'),
                        'children' => [
                            [ 'name' => 'Caderno',             'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Caderno') ],
                            [ 'name' => 'Bloco',               'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Bloco') ],
                            [ 'name' => 'Papel de Carta',      'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Papel de Carta') ],
                            [ 'name' => 'Envelope',            'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Envelope') ],
                            [ 'name' => 'Cartão Comemorativo', 'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Cartão Comemorativo') ],
                            [ 'name' => 'Lápis',               'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Lápis') ],
                            [ 'name' => 'Caneta',              'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Caneta') ],
                            [ 'name' => 'Borracha',            'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Borracha') ],
                            [ 'name' => 'Agenda',              'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Agenda') ],
                            [ 'name' => 'Planner',             'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Planner') ],
                            [ 'name' => 'Calendário',          'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Calendário') ],
                            [ 'name' => 'Pasta',               'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Pasta') ],
                            [ 'name' => 'Prancheta',           'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Prancheta') ],
                            [ 'name' => 'Alfinete',            'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Alfinete') ],
                            [ 'name' => 'Diário',              'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Diário') ],
                            [ 'name' => 'Cartão de Visita',    'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Cartão de Visita') ],
                            [ 'name' => 'Adesivo',             'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Adesivo') ],
                            [ 'name' => 'Marca Páginas',       'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('Marca Páginas') ],
                            [ 'name' => 'OUTROS',              'slug' => slug('Office') .'/'. slug('Papelaria') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Acessórios para Tecnologia',
                        'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia'),
                        'children' => [
                            [ 'name' => 'Organizador de Cabos',  'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Organizador de Cabos') ],
                            [ 'name' => 'Capa para Celular',     'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Capa para Celular') ],
                            [ 'name' => 'Adesivo para Notebook', 'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Adesivo para Notebook') ],
                            [ 'name' => 'Adesivo para Celular',  'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Adesivo para Celular') ],
                            [ 'name' => 'Capa para Notebook',    'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Capa para Notebook') ],
                            [ 'name' => 'Capa Para Tablet',      'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Capa Para Tablet') ],
                            [ 'name' => 'Mouse Pad',             'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Mouse Pad') ],
                            [ 'name' => 'Bolsa para Notebook',   'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('Bolsa para Notebook') ],
                            [ 'name' => 'OUTROS',                'slug' => slug('Office') .'/'. slug('Acessórios para Tecnologia') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Acessórios de Escritório',
                        'slug' => slug('Office') .'/'. slug('Acessórios de Escritório'),
                        'children' => [
                            [ 'name' => 'Quadro de Aviso',         'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Quadro de Aviso') ],
                            [ 'name' => 'Porta Lápis',             'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Porta Lápis') ],
                            [ 'name' => 'Peso de Papel',           'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Peso de Papel') ],
                            [ 'name' => 'Porta Cartões de Visita', 'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Porta Cartões de Visita') ],
                            [ 'name' => 'Ímã',                     'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Ímã') ],
                            [ 'name' => 'Carimbo',                 'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('Carimbo') ],
                            [ 'name' => 'OUTROS',                  'slug' => slug('Office') .'/'. slug('Acessórios de Escritório') .'/'. slug('OUTROS') ],
                        ],
                    ],
                    [
                        'name' => 'Outros',
                        'slug' => slug('Office') .'/'. slug('Outros'),
                    ],
                ],
            ],
        ];

        return $categories;
    }
}
